
package hai704i.tp2.demo.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeService", targetNamespace = "http://service.demo.tp2.hai704i/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeService {


    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "count", targetNamespace = "http://service.demo.tp2.hai704i/", className = "hai704i.tp2.demo.client.Count")
    @ResponseWrapper(localName = "countResponse", targetNamespace = "http://service.demo.tp2.hai704i/", className = "hai704i.tp2.demo.client.CountResponse")
    @Action(input = "http://service.demo.tp2.hai704i/EmployeeService/countRequest", output = "http://service.demo.tp2.hai704i/EmployeeService/countResponse")
    public int count();

    /**
     * 
     * @return
     *     returns java.util.List<hai704i.tp2.demo.client.Employee>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmployees", targetNamespace = "http://service.demo.tp2.hai704i/", className = "hai704i.tp2.demo.client.GetEmployees")
    @ResponseWrapper(localName = "getEmployeesResponse", targetNamespace = "http://service.demo.tp2.hai704i/", className = "hai704i.tp2.demo.client.GetEmployeesResponse")
    @Action(input = "http://service.demo.tp2.hai704i/EmployeeService/getEmployeesRequest", output = "http://service.demo.tp2.hai704i/EmployeeService/getEmployeesResponse")
    public List<Employee> getEmployees();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns hai704i.tp2.demo.client.Employee
     * @throws EmployeeAlreadyExistsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addEmployee", targetNamespace = "http://service.demo.tp2.hai704i/", className = "hai704i.tp2.demo.client.AddEmployee")
    @ResponseWrapper(localName = "addEmployeeResponse", targetNamespace = "http://service.demo.tp2.hai704i/", className = "hai704i.tp2.demo.client.AddEmployeeResponse")
    @Action(input = "http://service.demo.tp2.hai704i/EmployeeService/addEmployeeRequest", output = "http://service.demo.tp2.hai704i/EmployeeService/addEmployeeResponse", fault = {
        @FaultAction(className = EmployeeAlreadyExistsException_Exception.class, value = "http://service.demo.tp2.hai704i/EmployeeService/addEmployee/Fault/EmployeeAlreadyExistsException")
    })
    public Employee addEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws EmployeeAlreadyExistsException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns hai704i.tp2.demo.client.Employee
     * @throws EmployeeNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmployee", targetNamespace = "http://service.demo.tp2.hai704i/", className = "hai704i.tp2.demo.client.GetEmployee")
    @ResponseWrapper(localName = "getEmployeeResponse", targetNamespace = "http://service.demo.tp2.hai704i/", className = "hai704i.tp2.demo.client.GetEmployeeResponse")
    @Action(input = "http://service.demo.tp2.hai704i/EmployeeService/getEmployeeRequest", output = "http://service.demo.tp2.hai704i/EmployeeService/getEmployeeResponse", fault = {
        @FaultAction(className = EmployeeNotFoundException_Exception.class, value = "http://service.demo.tp2.hai704i/EmployeeService/getEmployee/Fault/EmployeeNotFoundException")
    })
    public Employee getEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws EmployeeNotFoundException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns hai704i.tp2.demo.client.Employee
     * @throws EmployeeNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateEmployee", targetNamespace = "http://service.demo.tp2.hai704i/", className = "hai704i.tp2.demo.client.UpdateEmployee")
    @ResponseWrapper(localName = "updateEmployeeResponse", targetNamespace = "http://service.demo.tp2.hai704i/", className = "hai704i.tp2.demo.client.UpdateEmployeeResponse")
    @Action(input = "http://service.demo.tp2.hai704i/EmployeeService/updateEmployeeRequest", output = "http://service.demo.tp2.hai704i/EmployeeService/updateEmployeeResponse", fault = {
        @FaultAction(className = EmployeeNotFoundException_Exception.class, value = "http://service.demo.tp2.hai704i/EmployeeService/updateEmployee/Fault/EmployeeNotFoundException")
    })
    public Employee updateEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws EmployeeNotFoundException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     * @throws EmployeeNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteEmployee", targetNamespace = "http://service.demo.tp2.hai704i/", className = "hai704i.tp2.demo.client.DeleteEmployee")
    @ResponseWrapper(localName = "deleteEmployeeResponse", targetNamespace = "http://service.demo.tp2.hai704i/", className = "hai704i.tp2.demo.client.DeleteEmployeeResponse")
    @Action(input = "http://service.demo.tp2.hai704i/EmployeeService/deleteEmployeeRequest", output = "http://service.demo.tp2.hai704i/EmployeeService/deleteEmployeeResponse", fault = {
        @FaultAction(className = EmployeeNotFoundException_Exception.class, value = "http://service.demo.tp2.hai704i/EmployeeService/deleteEmployee/Fault/EmployeeNotFoundException")
    })
    public boolean deleteEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws EmployeeNotFoundException_Exception
    ;

}
