
package hai704i.tp2.demo.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "EmployeeNotFoundException", targetNamespace = "http://service.demo.tp2.hai704i/")
public class EmployeeNotFoundException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private EmployeeNotFoundException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public EmployeeNotFoundException_Exception(String message, EmployeeNotFoundException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public EmployeeNotFoundException_Exception(String message, EmployeeNotFoundException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: hai704i.tp2.demo.client.EmployeeNotFoundException
     */
    public EmployeeNotFoundException getFaultInfo() {
        return faultInfo;
    }

}
